Test: setup tests, add tests for Home-page and Blog-page; small improvements

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,5 +1,11 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
+set -e
+
 npm run lint
 npm run format
+if [ $? -ne 0 ]; then
+  echo "Linting or formatting failed. Please fix the issues."
+  exit 1
+fi
